### ISSUE TITLE
Potentially overwrite some code

### ISSUE THREAD

**Issue by AlexanderTahtadjian** [AlexanderTahtadjian/components-on-a-grid#3]
@mackenzierose
I made some new changes to my code but its not really working how I wanted it. I feel like a overwrote it and I'm not exactly sure what to do to fix it

**Comment by MacKenzieRose** [comment]
If you've been committing your code to Github regularly, you can always go back to a previous version of it! 

That said, this particular assignment only requires a 2x2 grid, so one thing to take a look at and simplify would be your `grid-template-areas`.

If you need more specific help, tag me again!

**Comment by AlexanderTahtadjian** [comment]
I think the grid-template area is one of the main things I need help with, I think that's what giving me issues, but I'm not exactly sure how to fix it.

**Comment by MacKenzieRose** [comment]
So I would start with making it a 2x2 grid. Maybe something like:
`grid-template-areas:`
`"masthead masthead"`
`"main main2"`

Then, for the elements you need to be in the grid, you would target them something like this:
`.pano {`
`grid-area: masthead`
`}`

Let me know how that goes :)

**Comment by AlexanderTahtadjian** [comment]
It slightly worked, but its still looking like this
![Screenshot 2020-09-21 161629](https://user-images.githubusercontent.com/55193211/93816679-dbcf3200-fc25-11ea-8e6d-ec1deef7d6bd.jpg)

**Comment by MacKenzieRose** [comment]
So one of the things I'm seeing in your code is that you've got `grid-area: masthead` but not `grid-area: main` or `grid-area: main2`. So definitely make sure to add those.

The other thing to keep an eye out for is making sure your text content for the masthead is sitting in the right grid boxes. This might be easier to identify if you use the visual grid lines when you inspect your code :)

**Comment by AlexanderTahtadjian** [comment]
I added the grid-area: main and grid-area: main2 to where I believe they would go, but its still not working. Also I added some code to the figure, but I think its not applying it the way that I want it to.
